name : Test Secret and variables
on : push
jobs : 
  display_values :
    runs-on : ubuntu-latest
    steps :
      - run: |
          echo "${{ secrets.DATABASE_PASSWORD }}"
          echo "${{ vars.VERSION }}"
      - name: GitHub Script
        uses: actions/github-script@v7.0.1
        with:
          script: return "Mon retour"
